import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// Context
import { EditProvider } from "@/app/context/EditContext";
import { TargetProvider } from "@/app/context/TargetContext";

// Ant Design
import "@ant-design/v5-patch-for-react-19";
import { IndexProvider } from "./context/IndexContext";
import { PagesProvider } from "./context/PagesContext";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PagesProvider>
          <EditProvider>
            <IndexProvider>
              <TargetProvider>
                <Navbar />
                <div className="pb-[38px] pt-[90px] flex flex-col">
                  {children}
                </div>
                <Footer />
              </TargetProvider>
            </IndexProvider>
          </EditProvider>
        </PagesProvider>
      </body>
    </html>
  );
}
