import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// Context
import { SwitchProvider } from "@/app/context/SwitchContext"

// Ant Design
import '@ant-design/v5-patch-for-react-19';
import { IndexProvider } from "./context/IndexContext";
import { PagesProvider } from "./context/PagesContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PagesProvider>
        <SwitchProvider>
          <IndexProvider>
            <Navbar />
            <div className="min-h-[calc(100vh-38px)] flex flex-col">
            {children}
            </div>
          </IndexProvider>
        </SwitchProvider>
        </PagesProvider>
      </body>
    </html>
  );
}
